version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mhra-alerts-backend
    restart: unless-stopped
    ports:
      - "8081:8080"  # Changed from 8080 to 8081 to avoid conflict with RAG app
    volumes:
      # Use absolute paths for Synology
      - /volume1/docker/mhra-alerts/data:/app/data
      - /volume1/docker/mhra-alerts/logs:/app/logs
      - /volume1/docker/mhra-alerts/.env:/app/.env:ro
    environment:
      - DATABASE_URL=sqlite:////app/data/alerts.db
      - PYTHONUNBUFFERED=1
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - mhra-network
    user: "1026:100"  # Synology docker group

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://192.168.0.32:8081
    container_name: mhra-alerts-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - mhra-network

networks:
  mhra-network:
    driver: bridge